export const MOCK_TABLIST = [
	{
		id: 'bbd266f343d0',
		label: 'Lagerverwaltung',
		icon: 'LagerverwaltungIcon',
		url: '/lagerverwaltung',
	},
	{
		id: '95d91cb49c36',
		label: 'Dashboard',
		icon: 'DashboardIcon',
		url: '/dashboard',
	},
	{
		id: 'e1a6c42bc86e',
		label: 'Banking',
		icon: 'BankingIcon',
		url: '/banking',
	},
	{
		id: 'ae0311f10dc7',
		label: 'Telefonie',
		icon: 'TelefonieIcon',
		url: '/telefonie',
	},
	{
		id: '55df1c9329e6',
		label: 'Accounting',
		icon: 'AccountingIcon',
		url: '/accounting',
	},
	{
		id: '683f0a673b92',
		label: 'Verkauf',
		icon: 'VerkaufIcon',
		url: '/verkauf',
	},
	{
		id: '9802fa248cd6',
		label: 'Statistik',
		icon: 'StatistikIcon',
		url: '/statistik',
	},
	{
		id: '5d55731463e4',
		label: 'Post Office',
		icon: 'PostOfficeIcon',
		url: '/post-office',
	},
	{
		id: '130b259b86ee',
		label: 'Administration',
		icon: 'AdministrationIcon',
		url: '/administration',
	},
	{
		id: '56740a0a6297',
		label: 'Help',
		icon: 'HelpIcon',
		url: '/help',
	},
	{
		id: '7332f3f85082',
		label: 'Warenbestand',
		icon: 'WarenbestandIcon',
		url: '/warenbestand',
	},
	{
		id: 'f2374718e398',
		label: 'Auswahllisten',
		icon: 'AuswahllistenIcon',
		url: '/auswahllisten',
	},
	{
		id: '7ce13048705a',
		label: 'Einkauf',
		icon: 'EinkaufIcon',
		url: '/einkauf',
	},
	{
		id: '5a79e60a88cd',
		label: 'Rechn',
		icon: 'RechnIcon',
		url: '/rechn',
	},
] as const
